### ISSUE TITLE
consider using Limine as the bootloader

### ISSUE THREAD

**Issue by korewaChino** [FyraLabs/katsu#2]
Limine is an easy to set up bootloader thats supports multiple boot protocols, and designed for backwards compatibility

https://github.com/limine-bootloader/limine

Priority: Medium, optional
Contingency: only support GRUB for now

```[tasklist]
### Tasks
- [ ] Package Limine on Terra
- [ ] Add Limine as an option to katsu
- [ ] Develop OSTree plugin for Limine or figure out a way to support it
```
