### ISSUE TITLE
ARM images

### ISSUE THREAD

**Issue by korewaChino** [FyraLabs/katsu#6]
```[tasklist]
### Tasks
- [x] Refactor codebase
- [x] Write imaging module
- [x] Implement mount modules, or use sys-mount
- [ ] Write partitioning module
- [x] Write tests for ARM builds
- [x] Test ARM build on real hardware (Raspberry Pi)
```
