### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by korewaChino** [FyraLabs/katsu#7]
```[tasklist]
### Tasks
- [ ] Un-hardcode partitioning options
- [ ] Add partitioning options to config
- [ ] Make `builder` field optional for non top-level manifests
- [ ] Script dependency tree?
- [ ] Move dracut script in code instead of scripts
- [ ] Make use of Tera templating (like Ansible but for image building)
- [ ] (Future) Modularity via code modules and plugins?
```
